Notebook to compute the total cases predicted for each validation test. 

Each validation test represents a season with 52 weeks. For each of these weeks, the parameters of a log-normal distribution obtained from the log_normal_parameters.ipynb notebook. In order to sample paths from probabilistic forecasts, we use Gaussian Copulas to generate time-dependent paths.
The dependence structure is imposed via the autocorrelation parameter $\rho$ estimated from the historical series.
The process transforms the sampled values into uniform quantiles and then into correlated Gaussian variables,
generating new values through a linear relationship $Z_{t+1} = \rho Z_t + \sqrt{1-\rho^2}\varepsilon_t$. The values are then
mapped back to the original marginals, producing sample paths that preserve the predicted distributions
and that have a temporal dependence structure similar to the historical data.
Using these estimates, we calculate the WIS for each model in comparison with the observed values:

In [1]:
import numpy as np
import pandas as pd 
from epiweeks import Week
from numpy import log, exp
from itertools import product 
import matplotlib.pyplot as plt 
from scipy.stats import lognorm
from cum_preds_method import estimate_rho_correlation, cumulative_estimation
import matplotlib as mpl

# Definir a cor das bordas (spines) como cinza
mpl.rcParams['axes.edgecolor'] = 'gray'

# Definir a cor das linhas dos ticks maiores e menores como cinza
mpl.rcParams['xtick.color'] = 'gray'
mpl.rcParams['ytick.color'] = 'gray'
mpl.rcParams['xtick.labelcolor'] = 'black'
mpl.rcParams['ytick.labelcolor'] = 'black'
plt.rcParams['axes.labelsize'] = 16 # Axis labels
plt.rcParams['xtick.labelsize'] = 14  # X-axis tick labels
plt.rcParams['ytick.labelsize'] = 14  # Y-axis tick labels
plt.rcParams['font.size'] = 16  # General font size
FONT = 12

In [2]:
dict_models_name = {157: 'UERJ-SARIMAX-2', 156: 'Dengue oracle M2', 155: 'Dengue Oracle M1', 135:'GHR Model', 
                    133:'Chronos-Bolt', 139: 'Cornell PEH', 143: 'Model fourier-\ngravidade', 144:'Beat it', 150: 'LNN-AR_p-1', 
        145: 'CNNLSTM' , 141: 'Kaust Geohealth', 136: 'Imperial-TFT Model', 137: 'LSTM-RF model', 
                    138: 'TSMixer ZKI-PH4', 154: 'LNCC-SURGE-1', 152: 'LNCC-CLIDENGO-1', 134: 'ISI_Dengue_Model', 108:'IMPA-TECH'}

Load the data:

In [3]:
data = pd.read_csv('predictions/dengue_agg.csv.gz')
data.date = pd.to_datetime(data.date)
data = data.sort_values(by = 'date')

data['valid_test'] = None

data.loc[(data.date >= Week(2022, 41).startdate().strftime('%Y-%m-%d')) & (data.date <= Week(2023, 40).startdate().strftime('%Y-%m-%d')), 'valid_test'] = '1'  

data.loc[(data.date >= Week(2023, 41).startdate().strftime('%Y-%m-%d')) & (data.date <= Week(2024, 40).startdate().strftime('%Y-%m-%d')), 'valid_test'] = '2'

data.loc[(data.date >= Week(2024, 41).startdate().strftime('%Y-%m-%d')) & (data.date <= Week(2025, 40).startdate().strftime('%Y-%m-%d')), 'valid_test'] = '3' 


data.head()

            date   casos  uf valid_test
0     2010-01-03    73.0  AL       None
20550 2010-01-03    10.0  SC       None
1644  2010-01-03   138.0  CE       None
3288  2010-01-03    11.0  PB       None
18906 2010-01-03  1859.0  MS       None

In [4]:
df_agg = data.dropna().groupby(['uf', 'valid_test'])[['casos']].sum().reset_index().rename(columns = {'uf': 'state'})
df_agg['valid_test'] = df_agg['valid_test'].astype(int)
df_agg.head()

  state  valid_test    casos
0    AC           1   4735.0
1    AC           2   9740.0
2    AC           3  11533.0
3    AL           1   4779.0
4    AL           2  18667.0

In [5]:
data_23 = data.loc[(data.date >= Week(2022, 41).startdate().strftime('%Y-%m-%d')) & (data.date <= Week(2023, 40).startdate().strftime('%Y-%m-%d'))] 
data_24 = data.loc[(data.date >= Week(2023, 41).startdate().strftime('%Y-%m-%d')) & (data.date <= Week(2024, 40).startdate().strftime('%Y-%m-%d'))] 
data_25 = data.loc[(data.date >= Week(2024, 41).startdate().strftime('%Y-%m-%d')) & (data.date <= Week(2025, 40).startdate().strftime('%Y-%m-%d'))]

Load the predictions with log normal parameters estimated:

In [6]:
df_preds =  pd.read_csv('predictions/preds_CDF.csv')

df_preds = df_preds.loc[df_preds.state != 'ES']

df_preds.loc[df_preds.mu.isna(), ['mu', 'sigma']] = [0.01, 1/2]

df_preds['model_id'] = df_preds['model_id'].replace(dict_models_name)

df_preds['valid_test'] = None

df_preds.loc[(df_preds.date >= Week(2022, 41).startdate().strftime('%Y-%m-%d')) & (df_preds.date <= Week(2023, 40).startdate().strftime('%Y-%m-%d')), 'valid_test'] = '1'  

df_preds.loc[(df_preds.date >= Week(2023, 41).startdate().strftime('%Y-%m-%d')) & (df_preds.date <= Week(2024, 40).startdate().strftime('%Y-%m-%d')), 'valid_test'] = '2'

df_preds.loc[(df_preds.date >= Week(2024, 41).startdate().strftime('%Y-%m-%d')) & (df_preds.date <= Week(2025, 40).startdate().strftime('%Y-%m-%d')), 'valid_test'] = '3' 

df_preds.head()

,date,lower_95,lower_90,lower_80,lower_50,pred,upper_50,upper_80,upper_90,upper_95,valid_test,state,model_id,mu,sigma
0,2024-10-06,22.422222,40.304679,79.162970,244.274988,853.700012,2982.915845,9196.810733,18041.732884,32366.797486,3,RS,IMPA-TECH,6.748348,1.855412
1,2024-10-13,18.743651,34.187301,68.269130,216.515891,779.997873,2809.263104,8900.886361,17748.532118,32294.740637,3,RS,IMPA-TECH,6.657830,1.900458
2,2024-10-20,6.581569,12.226861,24.874887,81.165077,301.351891,1118.132411,3638.484729,7371.869282,13600.483733,3,RS,IMPA-TECH,5.704178,1.945792
3,2024-10-27,17.097895,32.060474,66.082749,220.934380,843.905436,3222.679992,10763.205908,22149.610067,41420.387215,3,RS,IMPA-TECH,6.736465,1.987314
4,2024-11-03,18.724941,35.572182,74.438413,255.270334,1003.039414,3940.407380,13500.169745,28209.239339,53454.977878,3,RS,IMPA-TECH,6.909363,2.029238

Get cumulative cases:

In [7]:
import polars as pl
import scipy.stats as st
from tqdm import tqdm

get the rhos:

In [8]:
dengue = pl.read_csv('predictions/dengue_agg.csv.gz')
dengue = dengue.rename({'uf': 'state'})
#dengue = dengue.with_columns(
#    np.log1p(pl.col('casos')).alias('log_casos')
#)
#dengue = dengue.filter(
#    pl.col('state') != 'ES',
#)[['state','date','casos']]
dengue = dengue[['state','date','casos']]

dengue = dengue.with_columns(
    pl.col("date").str.strptime(pl.Date, format="%Y-%m-%d").alias("date")
)

dengue = dengue.with_columns(pl.col('date').dt.year().alias('year'))

In [9]:
rhos = []
states = np.sort(dengue['state'].unique())
for state in states:
    history = dengue.filter(pl.col('state') == state, pl.col('date') < Week(2022, 41).startdate()).sort('date')['casos']
    rho = estimate_rho_correlation(history)
    rhos.append(rho)

rhos = pl.DataFrame({'state': states, 'rho': rhos})
rhos

shape: (27, 2)
┌───────┬──────────┐
│ state ┆ rho      │
│ ---   ┆ ---      │
│ str   ┆ f64      │
╞═══════╪══════════╡
│ AC    ┆ 0.928644 │
│ AL    ┆ 0.958959 │
│ AM    ┆ 0.908492 │
│ AP    ┆ 0.885807 │
│ BA    ┆ 0.954055 │
│ …     ┆ …        │
│ RS    ┆ 0.856013 │
│ SC    ┆ 0.865297 │
│ SE    ┆ 0.924875 │
│ SP    ┆ 0.969817 │
│ TO    ┆ 0.947521 │
└───────┴──────────┘

In [10]:
F_marginals = pl.from_pandas(df_preds[['date', 'valid_test', 'state', 'model_id', 'mu','sigma']].sort_values(by = 'date'))

F_marginals

shape: (68_952, 6)
┌────────────┬────────────┬───────┬──────────────────┬──────────┬──────────┐
│ date       ┆ valid_test ┆ state ┆ model_id         ┆ mu       ┆ sigma    │
│ ---        ┆ ---        ┆ ---   ┆ ---              ┆ ---      ┆ ---      │
│ str        ┆ str        ┆ str   ┆ str              ┆ f64      ┆ f64      │
╞════════════╪════════════╪═══════╪══════════════════╪══════════╪══════════╡
│ 2022-10-09 ┆ 1          ┆ RS    ┆ LNN-AR_p-1       ┆ 0.820083 ┆ 1.223897 │
│ 2022-10-09 ┆ 1          ┆ PR    ┆ Cornell PEH      ┆ 3.414897 ┆ 0.921169 │
│ 2022-10-09 ┆ 1          ┆ PA    ┆ Dengue oracle M2 ┆ 3.901297 ┆ 0.610181 │
│ 2022-10-09 ┆ 1          ┆ BA    ┆ LNCC-CLIDENGO-1  ┆ 3.005634 ┆ 0.826209 │
│ 2022-10-09 ┆ 1          ┆ RR    ┆ Dengue oracle M2 ┆ 2.101941 ┆ 1.251666 │
│ …          ┆ …          ┆ …     ┆ …                ┆ …        ┆ …        │
│ 2025-09-28 ┆ 3          ┆ RO    ┆ LNCC-CLIDENGO-1  ┆ 4.641981 ┆ 1.661095 │
│ 2025-09-28 ┆ 3          ┆ AL    ┆ Dengue Oracle M1 ┆ 4.750811 ┆ 0.772608 │
│ 2025-09-28 ┆ 3          ┆ PE    ┆ GHR Model        ┆ 4.530887 ┆ 0.701519 │
│ 2025-09-28 ┆ 3          ┆ RR    ┆ Dengue oracle M2 ┆ 1.806025 ┆ 1.565664 │
│ 2025-09-28 ┆ 3          ┆ MT    ┆ Chronos-Bolt     ┆ 4.736308 ┆ 0.286658 │
└────────────┴────────────┴───────┴──────────────────┴──────────┴──────────┘

In [11]:
F_marginals['model_id'].unique()

shape: (17,)
Series: 'model_id' [str]
[
	"Model fourier-
gravidade"
	"ISI_Dengue_Model"
	"IMPA-TECH"
	"LNCC-SURGE-1"
	"GHR Model"
	…
	"LNCC-CLIDENGO-1"
	"Cornell PEH"
	"Dengue oracle M2"
	"Imperial-TFT Model"
	"CNNLSTM"
]

In [12]:
F_marginals.filter(pl.col('state') == 'ES', pl.col('model_id') == 'Cornell PEH').shape[0]

0

In [13]:
states = rhos.sort('state')['state'].unique()
models = F_marginals['model_id'].unique()
valid_tests = F_marginals['valid_test'].unique()

results = []

for state in tqdm(states, desc="States"):
    for model in models:

        for val_test in valid_tests:

            rho = rhos.filter(pl.col('state') == state)['rho'].to_numpy()[0]

            if F_marginals.filter(pl.col('state') == state, pl.col('model_id') == model, 
                                  pl.col('valid_test') == val_test).shape[0] == 0: 
                pass

            else: 
                
                forecast_marginals = []

                for row in F_marginals.filter(pl.col('state') == state, pl.col('model_id') == model,
                                              pl.col('valid_test') == val_test).sort('date').iter_rows(named=True):
                    mu, sigma = row['mu'], row['sigma']
                    forecast_marginals.append(st.lognorm(s=sigma, scale=np.exp(mu)))
                cumu = cumulative_estimation(forecast_marginals, rho, n_paths=2000)
                results.append({
                    'state': state,
                    'model': model,
                    'valid_test': val_test, 
                    'lower_95': cumu[0],
                    'lower_90': cumu[1],
                    'lower_80': cumu[2],
                    'lower_50': cumu[3],
                    'pred': cumu[4],
                    'upper_50': cumu[5],
                    'upper_80': cumu[6],
                    'upper_90': cumu[7],
                    'upper_95': cumu[8],
                })
 
results = pl.DataFrame(results)

States: 100%|██████████| 27/27 [6:07:30<00:00, 816.70s/it]

In [15]:
results

shape: (1_326, 12)
┌───────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ state ┆ model      ┆ valid_test ┆ lower_95   ┆ … ┆ upper_50  ┆ upper_80  ┆ upper_90  ┆ upper_95  │
│ ---   ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str   ┆ str        ┆ str        ┆ f64        ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞═══════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ AM    ┆ Dengue     ┆ 2          ┆ 16759.8428 ┆ … ┆ 71907.113 ┆ 100553.14 ┆ 124257.27 ┆ 147251.37 │
│       ┆ oracle M2  ┆            ┆ 29         ┆   ┆ 401       ┆ 9907      ┆ 8974      ┆ 3682      │
│ AM    ┆ Dengue     ┆ 1          ┆ 9769.87692 ┆ … ┆ 47498.268 ┆ 70680.881 ┆ 89337.838 ┆ 114652.77 │
│       ┆ oracle M2  ┆            ┆ 5          ┆   ┆ 247       ┆ 515       ┆ 726       ┆ 8921      │
│ AM    ┆ Dengue     ┆ 3          ┆ 6896.69836 ┆ … ┆ 41140.491 ┆ 62087.388 ┆ 77388.479 ┆ 97357.538 │
│       ┆ oracle M2  ┆            ┆ 9          ┆   ┆ 865       ┆ 75        ┆ 655       ┆ 509       │
│ AM    ┆ Model      ┆ 2          ┆ 628.165746 ┆ … ┆ 12542.765 ┆ 26246.975 ┆ 40511.251 ┆ 62233.499 │
│       ┆ fourier-   ┆            ┆            ┆   ┆ 44        ┆ 856       ┆ 908       ┆ 865       │
│       ┆ gravidade  ┆            ┆            ┆   ┆           ┆           ┆           ┆           │
│ AM    ┆ Model      ┆ 1          ┆ 640.261728 ┆ … ┆ 12229.364 ┆ 25173.544 ┆ 38695.322 ┆ 53439.963 │
│       ┆ fourier-   ┆            ┆            ┆   ┆ 632       ┆ 941       ┆ 491       ┆ 204       │
│       ┆ gravidade  ┆            ┆            ┆   ┆           ┆           ┆           ┆           │
│ …     ┆ …          ┆ …          ┆ …          ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ PE    ┆ UERJ-SARIM ┆ 1          ┆ 4364.58055 ┆ … ┆ 31064.461 ┆ 48113.795 ┆ 64870.192 ┆ 84858.574 │
│       ┆ AX-2       ┆            ┆ 2          ┆   ┆ 722       ┆ 587       ┆ 649       ┆ 061       │
│ PE    ┆ UERJ-SARIM ┆ 3          ┆ 6415.58758 ┆ … ┆ 38898.134 ┆ 56515.332 ┆ 71106.229 ┆ 97899.219 │
│       ┆ AX-2       ┆            ┆ 2          ┆   ┆ 67        ┆ 591       ┆ 702       ┆ 798       │
│ PE    ┆ GHR Model  ┆ 2          ┆ 14568.4877 ┆ … ┆ 72343.033 ┆ 103047.48 ┆ 129543.86 ┆ 157458.45 │
│       ┆            ┆            ┆ 68         ┆   ┆ 072       ┆ 0477      ┆ 6537      ┆ 9006      │
│ PE    ┆ GHR Model  ┆ 1          ┆ 5922.30592 ┆ … ┆ 21536.443 ┆ 29205.188 ┆ 34990.071 ┆ 41497.434 │
│       ┆            ┆            ┆ 7          ┆   ┆ 499       ┆ 342       ┆ 15        ┆ 688       │
│ PE    ┆ GHR Model  ┆ 3          ┆ 7974.20336 ┆ … ┆ 30457.784 ┆ 42982.099 ┆ 53065.923 ┆ 62977.072 │
│       ┆            ┆            ┆ 5          ┆   ┆ 972       ┆ 979       ┆ 892       ┆ 171       │
└───────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [16]:
results.to_pandas().to_csv('results/cumulative_cases_ind_models_copule_method.csv.gz', index = False)